### ISSUE TITLE
繰り返し予定で複数の予定のうちの１つを編集した後に「設定した全ての予定を編集」

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/Calendars#6]
手順１
　繰り返し予定を登録（１日おき３回）
![1](https://cloud.githubusercontent.com/assets/10765970/17542163/4eafce2c-5f01-11e6-9dc0-d7deaf602b02.png)

手順２
　はじめの予定を編集（タイトルに２を付加）（この予定のみ）
![2](https://cloud.githubusercontent.com/assets/10765970/17542221/deafa43e-5f01-11e6-8d81-bfbed3375144.png)

手順３
　３つ目の予定を編集、ラジオボタン「設定した全ての予定を編集」を選択すると、
　その直後に「この予定のみ変更」のラジオボタンが１つだけになる。
![default](https://cloud.githubusercontent.com/assets/10765970/17542327/8a0616c4-5f02-11e6-9642-e39f849b0a90.png)

↓自動で以下の「この予定のみ」に切り替わる
![default](https://cloud.githubusercontent.com/assets/10765970/17542349/c9abaac8-5f02-11e6-80c5-6170440d03e2.png)

**Comment by to-hashimoto-3** [comment]
特定の予定のみで変更したとき、その対象予定は、この「予定のみ」だけ許可されるのは、Googleカレンダーの仕様に準拠しているためです。「設定している全て」を変更した場合、連続予定の先頭に移動するのも、GoogleカレンダーやNC2カレンダーと同一仕様です。手順としては、「これ以降に指定した全ての予定」をチェックしていただければ、希望の「予定のみ」をさけて、それ以外（以降）の予定をまとめて修正できるます。プログラム改造するのではなく、ヘルプ的なものを別途設ける（カレンダーの場合、これ以外にも、いくつか動きで文章で説明したほうがユーザーにやさしいとおもわれるものもあるので）のがいいと考えています。

**Comment by to-hashimoto-3** [comment]
上記のとおり、プログラム改造の問題ではないので、issueとしてはcloseさせていただきます。
