### ISSUE TITLE
（編集者や一般が）プライベートの予定を誤って公開空間（パブリック）、に変更した場合

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/Calendars#7]
（編集者や一般が）プライベートの予定を誤って公開空間（パブリック）、に変更すると、その後、直したり消す手段が無くなる。

プライベート登録のステータス（＝１）は、他のケースと区別し、公開対象を変えるのを許し、削除も許さないといけないのではないか。
（橋本さん8/10）

**Comment by RikaFujiwara** [comment]
削除や公開対象空間の変更は、一度発行したものについては、予定データの「現在」の空間で発行権限をもっていないとできない仕様。（NC3仕様。対象空間の変更が不可なのはカレンダー独特であるが、根本理由は削除できないのと同じ理由）

しかし上記の場面で、プライベートで決定していたものを他空間の予定に変えた場合
新空間ではまだ公開してないわけで、以前公開していたのはプライベート＝つまり自分しかみない。

この場合は、削除しても全然問題がないはず。
プライベートでの「公開」は厳密な意味での「公開」じゃないと考えることにする。

「発行済みか？」の判断はis_activeがプライベート空間以外でTRUEになっているデータが履歴中にある場合に限ること二する。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/06b1ad91efb1fb28500ef768d025e30d849844bd
上記Commitで対応
