### ISSUE TITLE
詳細編集でプレビューウィンドウが閉じない

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/Calendars#8]
詳細編集で「プレビュー」（目のボタン）をクリック、
プレビューウィンドウが表示されますが、×ボタンをくりっくしても、閉じませんでした。

![no5_](https://cloud.githubusercontent.com/assets/10765970/17543640/00897714-5f0d-11e6-8b18-84b83540876c.png)

**Comment by to-hashimoto-3** [comment]
現状は、動作なおっているので、closeとさせていただきます。
