### ISSUE TITLE
繰り返し（終了日）指定でおよそ２００回以上超えるような指定をするとエラー

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/Calendars#9]
終了日を指定した繰り返し予定について

日付：2016年8月10日
繰り返しの単位：1日ごと
終了日：２０１７年１０月１０日

といった、回数が２００を超えるような繰り返し指定で登録しようとするとエラーになりました。
エラー「127.0.0.1　ページは機能していません」

（繰り返し回数指定の場合は、すでに対応済み。メッセージ「カレンダーの繰り返し回数は１以上１００以下です。」が出る。OK。）

**Comment by to-hashimoto-3** [comment]
２００回制限は、nc3開発環境のxdebugで独自に設定した値でした。一般的なphp環境ではこの制限はありません。そしてini_set()でプログラム内で値変更可能。カレンダーでは、ここに値が指定されている場合、自己再帰回数の条件を1000回にひきあげ、かつ、カレンダー内部では、繰返しＭＡＸを366回にするようにしました。
